### ISSUE TITLE
Make a bookmarklet for Inform videos.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/bookmarklets#1]
per @githamm

 `[cq  comment="VIDEO PLACED BELOW"]<div data-config-widget-id="1" data-config-type="VideoPlayer/Single" data-config-tracking-group="90115" data-config-playlist-id="18464" data-config-video-id="31456944" data-config-site-section="denverpost" data-config-width="100%" data-config-height="9/16w" data-config-pb="AUTOPLAY-CODE" class="ndn_embed" style="width: 100%"></div>
[cq  comment="VIDEO PLACED ABOVE"]`

**Comment by freejoe76** [comment]
Here's another video markup, for reference: `<div data-config-widget-id="1" data-config-type="VideoPlayer/Single" data-config-tracking-group="90115" data-config-playlist-id="18477" data-config-video-id="31491920" data-config-site-section="denverpost" data-config-width="100%" data-config-height="9/16w" data-config-pb="AUTOPLAY-CODE" class="ndn_embed" style="width: 100%"></div>`

**Comment by schneidan** [comment]
This was released Feb 2., 2017.
