### ISSUE TITLE
Auto-Producer bug

### ISSUE THREAD

**Issue by danielboniface** [denverpost/bookmarklets#13]
Hey @schneidan, ever since the most recent update that split the sports and news menus, we're getting an error message every time we run a sports auto-producer task. The error message is:

"That's not a valid option. Try again, or Cancel to quit."

It seems to still work, but gives the error message every time.

**Comment by schneidan** [comment]
I'll take a look this morning. Thanks!

**Comment by schneidan** [comment]
I believe this should be fixed with the version I have just released (1.1.1).
