### ISSUE TITLE
Make a bookmarklet for newsletter subscriptions

### ISSUE THREAD

**Issue by freejoe76** [denverpost/bookmarklets#2]
Blocker: Finishing a satisfactory newsletter subscription page, @ericjlubbers let me know if you need help with that

**Comment by schneidan** [comment]
@ericjlubbers Can you give me a clearer description of what a newsletter bookmarklet would insert?

**Comment by schneidan** [comment]
All set. (Part of AUTO🤖PRODUCER™.)
