### ISSUE TITLE
Create Trump article "template" bookmarklet

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/bookmarklets#4]
Create bookmarklet that, once launched, checks the following set of sections, types the following set of tags and sets the primary section.

Sections:
Trump Administration
Politics
National Politics
Latest news
News
National News

Tags:
Donald Trump

Primary Section:
Trump Administration

**Comment by schneidan** [comment]
This has become an entirely new bookmarklet known as AUTO-PRODUCER™, as well as adding the Apple News Politics section. Further options added, and more can be requested via a spreadsheet. Ask @ericjlubbers for access.
