### ISSUE TITLE
Add Nouner functionality to Auto-Producer sports

### ISSUE THREAD

**Issue by danielboniface** [denverpost/bookmarklets#7]
Create functionality that the Auto-Producer will also run the Nouner for the relevant sport list (i.e. Broncos, Rockies, Nuggets, Avs, Colleges, etc...) when a producer runs the Auto-Producer on that type of sports story.

Potential challenges: Nouner currently only works in text view when a story is first opened or saved.

**Comment by schneidan** [comment]
Just doesn't look very doable right now, as discussed in meatspace.
