### ISSUE TITLE
Check a specific group in Notifications widget when Auto-Producer is run

### ISSUE THREAD

**Issue by danielboniface** [denverpost/bookmarklets#8]
Add functionality to Auto-Producer, that when Auto-Producer runs on a sports story, it checks the box in the Notifications widget to alert the DPSP Online group.

If the box is already checked, Auto-Producer leaves it checked and does not uncheck it.

**Comment by schneidan** [comment]
This is released and will be done on any story that checked the "Sports" section checkbox.
